### ISSUE TITLE
transport: policy suboptimal API

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-go-driver#229]
The anonymous function based API 

```
type HostSelectionPolicy interface {
	PlanIter(QueryInfo) func() *Node
}

// WrapperPolicy is used to combine round-robin policies with token aware ones.
type WrapperPolicy interface {
	HostSelectionPolicy
	WrapPlan([]*Node) func() *Node
}
```

Causes loads of small allocations and kills perf of pickConn.

![image](https://user-images.githubusercontent.com/1617930/165970395-2ed43a05-e6d9-4f8e-abf9-0bb19d279f03.png)

I added cache to fix another issue with slices allocation but it seems to me that the whole API needs to be reworked.

We have two options

Option 1: return the whole slice, less changes but stupid

```
type HostSelectionPolicy interface {
	PlanIter(QueryInfo) []*Node
}
```

Option 2: more changes but correct - it would allow to remove my fix that adds RW mutex

```
type HostSelectionPolicy interface {
	Iter(QueryInfo, i) *Node
}
```

In that case user controls the iteration state and requests Node at position i.
Typically this is always 0 and we can save the effort and simplify the APIs.

**Comment by mmatczuk** [comment]
Please drop f60c4da1 and proceed with option 2.

**Comment by Michal-Leszczynski** [comment]
What about adding some preprocessing to `cluster`, so that for each token, we store a slice of it's replica nodes grouped by local DC (if local DC is specified). I believe they do something similar in **gocql**. This way, `picConn` function would only have to worry about RR (all interesting nodes are already calculated) and would basically consist only of a return statement. This make some sense, because replica nodes are fixed for a given token.

Moreover, we don't need to allocate many (usually 256 * nodes), small (size of RF) slices, we can allocate 1 big slice (we know it's length) and store slices of that slice for every token. 

Finally, right now I am experimenting with removing all allocations from HSP, but it seems like it can only be achieved by writing duplicated and difficult to develop and maintain code. The reason is that without slice or function allocations, token aware policies don't really have a nice way of communicating with RR policies (like passing slice of replica nodes to them), so they have to do their work on their own.

What do you think about that?
@mmatczuk

**Comment by Michal-Leszczynski** [comment]
This approach would go along with the second option that you described, so that the process of `picConn` is allocation free.
