### ISSUE TITLE
Squash all HostSelection policies

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla-go-driver#255]
We have:
* `RoundRobinPolicy`
* `DCAwareRoundRobinPolicy`
* `TokenAwarePolicy`

The `RoundRobinPolicy` is a special case of `DCAwareRoundRobinPolicy` when there is a single DC and should not be used in multiple DC setting.

With new API the round robin behavior can be put to the `TokenAwarePolicy`.

The new API can be specified as

```
type HostSelectionPolicy interface {
	Node(QueryInfo, int) *Node
}
```

Node function returns n-th node for a query - typically 0. The position information can be kept in `Query` and used in `pickConn` function. This API has many benefits, it does not allocate memory on heap for slices or filter functions it is also lazy and avoids evaluation of all replicas when only the first is needed.

**Comment by mmatczuk** [comment]
cc @piodul

**Comment by mmatczuk** [comment]
IMO the latency measurements is an external component that can be plugged to a new implementation on construction and no additional function parameter is required.

**Comment by martin-sucha** [comment]
> IMO the latency measurements is an external component that can be plugged to a new implementation

That is true.

What I meant is that retries should go to a different node than the original attempt. The built-in policy always guarantees that just by iterating over the topology. The topology is "snapshotted" at the time when the QueryInfo is created because the topology uses read-copy-update. So even if the topology changes between the original attempt and the retry, the builtin policy still uses the same topology for the retry as the original attempt.

A latency aware policy would select the node with the lowest latency for the initial attempt, second lowest latency for the retry etc. However, the latency measurements can change over time and there isn't a similar read-copy-update mechanism that could be used to snapshot the measurements, so the ordering of nodes by latency can change between the initial attempt and the retry. This could lead to retry being sent to the same node as for the initial attempt. If the policy could snapshot the measurements at the initial attempts (and store pointer to this snapshot in the state), it would be able to guarantee that retries are never made to the same hosts as before.

I don't know how important it is in practice to guarantee that retries are always to different nodes than before.

We should probably also explicitly document in the interface how the caller of `Node()` determines how many attempts to try, resp. how the policy indicates that there are no more hosts to try. I'd like to avoid situation as in  https://github.com/gocql/gocql/issues/1259#issuecomment-526130900 for this new interface.

**Comment by mmatczuk** [comment]
Any additional context info can go to QueryInfo if needed.

**Comment by martin-sucha** [comment]
That is a good point, extending the QueryInfo would work in that case. :+1:
